### PR TITLE
Rky has completed the file and need permission to merge

### PR DESCRIPTION
**Pull request by rukiye3871**
added advices for the project

### CODE REVIEW

**Comment by bedriye1** [comment]
good job guy. you can merge it .thx.

**Review by rukiye3871 — COMMENTED** [review]
I am not sure what am I doing only trying and seeing

**Comment by bedriye1** [comment]
you can click merge pull request and than pull it to your local repocitory.

**Comment by bedriye1** [comment]
now we can see your branch in the origin master. we pull it our local .

**Pull request merged**
